"""Add gradient_type, gradient_direction, and frame_color columns

Revision ID: 54fea013d87f
Revises: 59f4f3c9d1c9
Create Date: 2025-05-02 16:14:42.579472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fea013d87f'
down_revision = '59f4f3c9d1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gradient_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gradient_direction', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('frame_color', sa.String(length=20), nullable=True))

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_confirm_token',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_confirm_token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('os')

    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.drop_column('frame_color')
        batch_op.drop_column('gradient_direction')
        batch_op.drop_column('gradient_type')

    # ### end Alembic commands ###
